#!/bin/bash
# Usage: ./solve instances [ time_limit ]

if [ -z "$1" ]; then
    echo "./solve instances"
    exit
fi

THREADS=16

start=`date +%s`

instances=$1
if [ -z "$2" ]; then
    time_limit=1
else
    time_limit=$2
fi

/bin/rm -fr TOURS-$instances
/bin/rm -fr TMP
mkdir -p TOURS-$instances
mkdir -p TMP

for FILE in `ls $instances/*.ctsptw` ;
do
    name=$(echo "$FILE" | cut -f 2 -d '/' | cut -f 1 -d '.')
    par=TMP/$name.pid$$.par
    echo "PROBLEM_FILE = $FILE" > $par
    echo "CTSP_TRANSFORM = YES" >> $par
    echo "SEED = 1" >> $par
    echo "TIME_LIMIT = $time_limit" >> $par
    echo "TRACE_LEVEL = 0" >> $par
    echo "TOUR_FILE = TOURS-$instances/$name.tour" >> $par
#    echo "HASHING = NO" >> $par
#    echo "MERGING = NO" >> $par
#    echo "SUBGRADIENT = NO" >> $par
#    echo "TIME_WINDOWS = YES" >> $par
    ./LKH $par &
    until [ $(jobs -r | grep ./LKH | wc -l) -lt $THREADS ]; do
        sleep 0.01
    done
done
wait

./score $instances

/bin/rm -fr TMP

end=`date +%s`
echo "Runtime:" $((end-start)) "seconds"
